"""Vapour-rail unification package.

U0 freezes the canonical manifest union. VR-4 adds typed NASA CEA polynomial
evaluators (``nasa_cea``). VR-4b registers nasa7/nasa9/shomate as **runtime**
catalog evaluator families (dormant rows; energetics only — Ellingham keeps
phase-transition breakpoints). VR-7 adds charge-alias canonicalization for
ledger/cache-safe oxyanion names. VR-8 adds Group-A/B + monatomic-O acquisition
transcription (``trace_acquisition``). VR-10 adds the warm calibration runner
library and progressive-validation reports (``calibration``). Later VR chunks
add runtime cutovers under this package.
"""

from __future__ import annotations
from simulator.vapour_rail.catalog import (
    CHARGE_ALIAS_CANONICAL,
    canonicalize_charge_alias,
)
from simulator.vapour_rail.calibration import (
    DEFAULT_SIDECAR_PATH as VAPOUR_RAIL_CALIBRATION_SIDECAR,
    FROZEN_ANALYTICAL_FAMILIES,
    ProgressiveValidationReport,
    build_progressive_validation_report,
    load_vapour_rail_calibration_sidecar,
)
from simulator.vapour_rail.trace_acquisition import (
    GROUP_A_IDS,
    GROUP_B_IDS,
    MONATOMIC_OXYGEN_ID,
    PO2_EXPONENT_ATOMIC_O,
    list_pending_validation,
    load_trace_acquisition,
)
from simulator.vapour_rail.u0_manifest import (
    ASSOCIATION_POLYMER_IDS,
    CARRIER_ONLY_IDS,
    COLLISION_GAS_IDS,
    FEEDSTOCK_DELTA_IDS,
    GROUP_A_GAS_IDS,
    GROUP_B_ELEMENT_IDS,
    GROUP_B_GAS_IDS,
    REFRACTORY_GAS_IDS_RAW,
    VAPOROCK_42_IDS,
    build_u0_manifest,
    canonicalize_gas_id,
    load_u0_manifest,
)
from simulator.vapour_rail.activity import (
    BOUND_NOT_POINT,
    REASON_HENRIAN_GAMMA_UNMEASURED,
    ActivityInputDeclaration,
    ActivityRefusalCode,
    ActivityVerdictKind,
    AssemblageIdentity,
    BoundDirection,
    CondensedPhaseActivityProvider,
    MageminAssemblageEvidence,
    PhaseEndmemberMap,
    SourceReactionActivity,
    StandardStateIdentity,
    StateFingerprint,
    ThermoEnginePotentialEvidence,
    activity_from_chemical_potentials,
    composition_fingerprint,
    henrian_unknown_gamma_upper_bound,
    prove_pressure_monotone_nondecreasing_in_activity,
    validation_row_may_certify,
)
from simulator.vapour_rail.kinetics_anchors import (
    AlphaProvenance,
    KineticsAnchorRecord,
    KineticsExperimentalRegime,
    alpha_provenance_from_mapping,
    assert_alpha_source_not_vaporock,
    load_kems_anchors,
    load_langmuir_anchors,
    regimes_remain_distinct,
)
from simulator.vapour_rail.batch import (
    FLUX_ACTIVATION_EPOCH_PRE_RG,
    FLUX_ACTIVATION_EPOCH_RG_MANIFEST,
    FluxActivationContext,
    IncompleteVapourBatchError,
    VapourAnswer,
    VapourBatch,
    VapourRequestConstructionError,
)
from simulator.vapour_rail.request import (
    ProviderDomainCandidate,
    RequestRule,
    VapourResolveState,
    build_request,
    chemical_potential_channel_refusal,
    emit_request_rules,
    resolve_vapour_batch,
)
from simulator.vapour_rail.channels import (
    CHANNEL_O2,
    CHANNEL_REGISTRY,
    ChannelCompositionRefusal,
    ChannelConstructionError,
    ChannelEvaluationError,
    ChannelVerdictKind,
    CompiledReactionTerm,
    GasChannelPotential,
    ReactionThermoInputs,
    attempt_channel_composition,
    channel_linear_mass_action_factor,
    channel_log10_contribution,
    compile_channel_term_from_binding,
    derived_exponent,
    o2_potential_from_pO2_bar,
    resolve_channel_potential,
)

__all__ = [
    "ASSOCIATION_POLYMER_IDS",
    "CARRIER_ONLY_IDS",
    "CHARGE_ALIAS_CANONICAL",
    "COLLISION_GAS_IDS",
    "FEEDSTOCK_DELTA_IDS",
    "GROUP_A_GAS_IDS",
    "GROUP_A_IDS",
    "GROUP_B_ELEMENT_IDS",
    "GROUP_B_GAS_IDS",
    "GROUP_B_IDS",
    "MONATOMIC_OXYGEN_ID",
    "PO2_EXPONENT_ATOMIC_O",
    "REFRACTORY_GAS_IDS_RAW",
    "VAPOROCK_42_IDS",
    "VAPOUR_RAIL_CALIBRATION_SIDECAR",
    "FROZEN_ANALYTICAL_FAMILIES",
    "FLUX_ACTIVATION_EPOCH_PRE_RG",
    "FLUX_ACTIVATION_EPOCH_RG_MANIFEST",
    "FluxActivationContext",
    "ProgressiveValidationReport",
    "build_progressive_validation_report",
    "build_u0_manifest",
    "canonicalize_charge_alias",
    "canonicalize_gas_id",
    "list_pending_validation",
    "load_trace_acquisition",
    "load_u0_manifest",
    "load_vapour_rail_calibration_sidecar",
    "BOUND_NOT_POINT",
    "REASON_HENRIAN_GAMMA_UNMEASURED",
    "ActivityInputDeclaration",
    "ActivityRefusalCode",
    "ActivityVerdictKind",
    "AlphaProvenance",
    "AssemblageIdentity",
    "BoundDirection",
    "CondensedPhaseActivityProvider",
    "KineticsAnchorRecord",
    "KineticsExperimentalRegime",
    "MageminAssemblageEvidence",
    "PhaseEndmemberMap",
    "SourceReactionActivity",
    "StandardStateIdentity",
    "StateFingerprint",
    "ThermoEnginePotentialEvidence",
    "activity_from_chemical_potentials",
    "alpha_provenance_from_mapping",
    "assert_alpha_source_not_vaporock",
    "composition_fingerprint",
    "henrian_unknown_gamma_upper_bound",
    "load_kems_anchors",
    "load_langmuir_anchors",
    "prove_pressure_monotone_nondecreasing_in_activity",
    "regimes_remain_distinct",
    "validation_row_may_certify",
    "IncompleteVapourBatchError",
    "ProviderDomainCandidate",
    "RequestRule",
    "VapourAnswer",
    "VapourBatch",
    "VapourRequestConstructionError",
    "VapourResolveState",
    "build_request",
    "chemical_potential_channel_refusal",
    "emit_request_rules",
    "resolve_vapour_batch",
    "CHANNEL_O2",
    "CHANNEL_REGISTRY",
    "ChannelCompositionRefusal",
    "ChannelConstructionError",
    "ChannelEvaluationError",
    "ChannelVerdictKind",
    "CompiledReactionTerm",
    "GasChannelPotential",
    "ReactionThermoInputs",
    "attempt_channel_composition",
    "channel_linear_mass_action_factor",
    "channel_log10_contribution",
    "compile_channel_term_from_binding",
    "derived_exponent",
    "o2_potential_from_pO2_bar",
    "resolve_channel_potential",
]
