"""Empirical battery schema v2.1 — records, identity, validity, scorer."""

from simulator.battery.enums import (
    QUANTITY_UNITS,
    AdmissionStatus,
    Authority,
    Engine,
    EvidenceClass,
    ExecutionState,
    ExperimentKind,
    IdentityEqualKind,
    MethodToken,
    NoticeKind,
    PerBasis,
    Phase,
    Quantity,
    Rail,
    ReferenceStateConvention,
    RefusalReason,
    ResidualStatus,
    StateTag,
)
from simulator.battery.identity import (
    Identity,
    IdentityEqualOutcome,
    atm_to_pa,
    bar_to_pa,
    celsius_to_kelvin,
    identity_equal,
    kcal_th_to_kJ_per_mol,
    log10K_from_delta_fG_kJ_mol,
    rescale_energy_per_basis,
    standard_pressure_delta_g_kJ_per_mol,
)
from simulator.battery.records import (
    Experiment,
    Observation,
    Residual,
    State,
    Work,
    union_notices,
)
from simulator.battery.score import SCORE_ENGINE_SET, score_store
from simulator.battery.validate import ValidationReport, validate_corpus
from simulator.battery.validity import (
    GateOutcome,
    background_pressure_high,
    effusion_regime_unverified,
    run_validity_gates,
    table_self_consistency,
    underdetermined_apparatus,
)

__all__ = (
    "QUANTITY_UNITS",
    "AdmissionStatus",
    "Authority",
    "Engine",
    "EvidenceClass",
    "ExecutionState",
    "Experiment",
    "ExperimentKind",
    "GateOutcome",
    "Identity",
    "IdentityEqualKind",
    "IdentityEqualOutcome",
    "MethodToken",
    "NoticeKind",
    "Observation",
    "PerBasis",
    "Phase",
    "Quantity",
    "Rail",
    "SCORE_ENGINE_SET",
    "ReferenceStateConvention",
    "RefusalReason",
    "Residual",
    "ResidualStatus",
    "State",
    "StateTag",
    "ValidationReport",
    "Work",
    "atm_to_pa",
    "background_pressure_high",
    "bar_to_pa",
    "celsius_to_kelvin",
    "effusion_regime_unverified",
    "identity_equal",
    "kcal_th_to_kJ_per_mol",
    "log10K_from_delta_fG_kJ_mol",
    "rescale_energy_per_basis",
    "run_validity_gates",
    "score_store",
    "standard_pressure_delta_g_kJ_per_mol",
    "table_self_consistency",
    "underdetermined_apparatus",
    "union_notices",
    "validate_corpus",
)
